# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprestrict', '0006_auto_20161013_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprange',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
