Document: django-iprestrict
Title: Debian django-iprestrict Manual
Author: <insert document author here>
Abstract: This manual describes what django-iprestrict is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/django-iprestrict/django-iprestrict.sgml.gz

Format: postscript
Files: /usr/share/doc/django-iprestrict/django-iprestrict.ps.gz

Format: text
Files: /usr/share/doc/django-iprestrict/django-iprestrict.text.gz

Format: HTML
Index: /usr/share/doc/django-iprestrict/html/index.html
Files: /usr/share/doc/django-iprestrict/html/*.html
